name: keploy-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Keploy CLI
        run: curl -s https://keploy.io/install.sh | bash

      - name: Install Dependencies
        run: npm install

      - name: Start App and Run Keploy Tests
        run: |
          nohup npm start > app.log 2>&1 &
          sleep 15  # Give enough time for your app to start
          keploy test -c "npm start" -r true

      - name: Stop Running Containers
        if: always()
        run: docker ps -q | xargs -r docker stop
