name: keploy-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Keploy CLI
        run: curl -s https://raw.githubusercontent.com/keploy/keploy/main/install.sh | bash

      - name: Install dependencies
        run: npm install

      - name: Start App and Run Keploy Tests
        run: |
          nohup npm start > app.log 2>&1 &
          sleep 15
          keploy test -c "npm start" -r true

      - name: Stop containers
        run: |
          docker ps -q | xargs -r docker stop
