name: keploy-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Keploy CLI (Manual Binary Method)
        run: |
          mkdir -p $HOME/.keploy/bin
          curl -Lo $HOME/.keploy/bin/keploy https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64
          chmod +x $HOME/.keploy/bin/keploy
          echo "$HOME/.keploy/bin" >> $GITHUB_PATH

      - name: Confirm Keploy Installed
        run: |
          export PATH="$HOME/.keploy/bin:$PATH"
          keploy version

      - name: Set up JDK 21 with Oracle
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build Spring Boot Project
        run: |
          cd onelinedaily-backend
          mvn clean package

      - name: Start Backend and Run Keploy Tests
        run: |
          cd onelinedaily-backend
          nohup java -jar target/*.jar &
          sleep 10
          export PATH="$HOME/.keploy/bin:$PATH"
          keploy test -c "java -jar target/*.jar" -r true
