name: keploy-test

on:
  push:
    branches:
      - main

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and Install Keploy CLI Safely
        run: |
          mkdir -p $HOME/.keploy/bin
          curl -L https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64 -o $HOME/.keploy/bin/keploy
          chmod +x $HOME/.keploy/bin/keploy
          echo "$HOME/.keploy/bin" >> $GITHUB_PATH
          ls -lah $HOME/.keploy/bin
          file $HOME/.keploy/bin/keploy  # Confirm it's a binary

      - name: Verify Keploy Installation
        run: |
          export PATH="$HOME/.keploy/bin:$PATH"
          $HOME/.keploy/bin/keploy version

      - name: Set up JDK 21 (Oracle)
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build Spring Boot Project
        run: |
          cd onelinedaily-backend
          mvn clean package

      - name: Start Spring Boot and Run Keploy Tests
        run: |
          cd onelinedaily-backend
          nohup java -jar target/*.jar &
          sleep 10
          export PATH="$HOME/.keploy/bin:$PATH"
          keploy test -c "java -jar target/*.jar" -r true
