name: Keploy API Testing

on:
  push:
    branches:
      - main

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Keploy CLI
        run: |
          curl -Lo keploy.tar.gz https://github.com/keploy/keploy/releases/download/v2.6.14/keploy_linux_amd64.tar.gz
          tar -xzf keploy.tar.gz
          chmod +x keploy
          sudo mv keploy /usr/local/bin/keploy

      - name: Verify Keploy Installation
        run: keploy version

      - name: Set up JDK 21 with Oracle
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build Spring Boot Project (Maven)
        run: |
          mvn clean package
        working-directory: onelinedaily-backend

      - name: Start Backend and Run Keploy Tests
        run: |
          nohup java -jar target/*.jar &
          sleep 10
          keploy test -c "java -jar target/*.jar" -r true
        working-directory: onelinedaily-backend
